spring.application.name=database_connection

spring.datasource.url=jdbc:mysql://localhost:5432/SpringBoot
spring.datasource.username=root
spring.datasource.password=101108

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true